# Generated by Django 3.1.1 on 2020-09-14 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TPO_app', '0002_jobinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobinfo',
            name='graduation',
            field=models.DecimalField(decimal_places=2, max_digits=19),
        ),
    ]
