# Generated by Django 3.1.1 on 2020-09-14 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TPO_app', '0003_auto_20200914_1026'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventname', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('eventdate', models.CharField(max_length=200)),
            ],
        ),
    ]
