# Generated by Django 3.1.1 on 2020-09-14 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TPO_app', '0004_eventinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=200)),
                ('role', models.CharField(max_length=200)),
                ('salary', models.CharField(max_length=200)),
            ],
        ),
    ]
